apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k8s-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: k8s-pv

