apiVersion: apps/v1
kind: Deployment
metadata:
  name: container2
  labels:
    app: container2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container2
  template:
    metadata:
      labels:
        app: container2
    spec:
      containers:
      - name: container2
        image: us-east1-docker.pkg.dev/cloudk8s-389823/reg2/image-dir
        ports:
        - containerPort: 6001
        volumeMounts:
            - name: k8s-volume
              mountPath: /JAYA_PV_dir
      volumes:
        - name: k8s-volume
          persistentVolumeClaim:
            claimName: k8s-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: container2
spec:
  type: LoadBalancer
  selector:
    app: container2
  ports:
    - protocol: TCP
      port: 6001
      targetPort: 6001


