apiVersion: apps/v1
kind: Deployment
metadata:
  name: container1
  labels:
    app: container1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container1
  template:
    metadata:
      labels:
        app: container1
    spec:
      containers:
      - name: container1
        image: us-east1-docker.pkg.dev/cloudk8s-389823/reg1/image-dir
        ports:
        - containerPort: 6000
        volumeMounts:
            - name: k8s-volume
              mountPath: /JAYA_PV_dir
      volumes:
        - name: k8s-volume
          persistentVolumeClaim:
            claimName: k8s-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: container1
spec:
  type: LoadBalancer
  selector:
    app: container1
  ports:
    - protocol: TCP
      port: 6000
      targetPort: 6000


